package debugreport

import (
	"fmt"
	"strconv"
	"strings"
	"time"
)

// Markdown renders the report for pasting into an issue.
//
// Shaped for the reader, not the collector: the summary at the top is what a
// maintainer needs in the first five seconds, and everything else is folded
// into <details> blocks so a long report does not bury the thread. GitHub
// renders those collapsed, and a plain-text viewer shows them expanded, which
// is the right behaviour in both places.
func (r Report) Markdown() string {
	var b strings.Builder

	b.WriteString("## GobboNet debug report\n\n")
	r.writeSummary(&b)

	if r.Network != nil {
		r.writeNetwork(&b)
	}
	if r.Runtime != nil {
		r.writeRuntime(&b)
	}
	if r.System != nil {
		r.writeSystem(&b)
	}
	if r.Config != nil {
		r.writeConfig(&b)
	}
	if r.Data != nil {
		r.writeData(&b)
	}
	if r.Models != nil {
		r.writeModels(&b)
	}

	if len(r.Notes) > 0 {
		b.WriteString("\n### Not collected\n\n")
		for _, n := range r.Notes {
			b.WriteString("- " + n + "\n")
		}
	}

	b.WriteString("\n<sub>Generated by `gobbonet debug-report` · schema " +
		strconv.Itoa(r.Schema))
	if r.System != nil && r.System.HomeRedacted {
		b.WriteString(" · home directory redacted")
	}
	b.WriteString("</sub>\n")

	return b.String()
}

func (r Report) writeSummary(b *strings.Builder) {
	row := func(k, v string) {
		if v != "" {
			fmt.Fprintf(b, "| %s | %s |\n", k, v)
		}
	}
	b.WriteString("| | |\n|---|---|\n")
	row("version", code(r.Build.Version))
	row("build origin", r.Build.Origin+" — "+r.Build.OriginDetail)
	if r.Build.StampMismatch != "" {
		row("⚠ stamp", r.Build.StampMismatch)
	}
	row("platform", r.Build.OS+"/"+r.Build.Arch+" · "+r.Build.GoVersion)
	if r.System != nil && r.System.OSVersion != "" {
		row("os", r.System.OSVersion)
	}
	if r.Config != nil {
		row("mode", r.Config.Mode)
	}
	if r.Network != nil {
		row("upstream", r.Network.Verdict)
	}
	if r.Runtime != nil && r.Runtime.Supervisor != nil && r.Runtime.Supervisor.LastError != "" {
		row("⚠ llama-server", code(r.Runtime.Supervisor.LastError))
	}
	row("auth", fmt.Sprintf("required=%t · secret=%s · session=%s",
		r.Auth.Required, r.Auth.SecretFormat, r.Auth.Session))
	row("generated", r.Generated)
	b.WriteString("\n")
}

func (r Report) writeNetwork(b *strings.Builder) {
	n := r.Network
	open(b, "Connectivity — "+n.Verdict)

	b.WriteString("| hop | status | ms | detail |\n|---|---|---|---|\n")
	for _, h := range n.Hops {
		status := "—"
		if h.Status > 0 {
			status = strconv.Itoa(h.Status)
		}
		detail := h.Error
		if detail == "" {
			detail = h.Note
		}
		if detail == "" {
			detail = h.Body
		}
		fmt.Fprintf(b, "| %s<br><sub>%s</sub> | %s | %d | %s |\n",
			h.Name, h.URL, status, h.LatencyMS, cell(detail))
	}

	if tc := n.TestCompletion; tc != nil {
		b.WriteString("\n**Live test message**\n\n")
		if tc.OK {
			fmt.Fprintf(b, "- succeeded in %d ms — model `%s` replied %s\n",
				tc.LatencyMS, tc.Model, code(tc.Reply))
		} else {
			fmt.Fprintf(b, "- FAILED after %d ms — status %d\n", tc.LatencyMS, tc.Status)
			if tc.Error != "" {
				b.WriteString("\n```\n" + tc.Error + "\n```\n")
			}
		}
	}
	closeDetails(b)
}

func (r Report) writeRuntime(b *strings.Builder) {
	rt := r.Runtime
	open(b, "Runtime")

	fmt.Fprintf(b, "- pid %d · mode %s · hot-swap %t · upstream_ok %t\n",
		rt.PID, rt.Mode, rt.Hotswap, rt.UpstreamOK)
	if rt.Uptime != "" {
		fmt.Fprintf(b, "- uptime %s\n", rt.Uptime)
	}

	if l := rt.Listener; l != nil {
		fmt.Fprintf(b, "- listening on %s:%d · LAN reachable %t\n", l.Host, l.Port, l.LANReachable)
		if l.FellBack {
			fmt.Fprintf(b, "- ⚠ wide bind refused, fell back to loopback: %s\n", l.BindError)
		}
		for _, a := range l.Addresses {
			fmt.Fprintf(b, "  - %s\n", a)
		}
	}

	if s := rt.Supervisor; s != nil {
		fmt.Fprintf(b, "\n**llama-server** — phase `%s`", s.Phase)
		if s.Model != "" {
			fmt.Fprintf(b, " · model `%s`", s.Model)
		}
		b.WriteString("\n")
		if s.LastError != "" {
			b.WriteString("\n" + "```\n" + s.LastError + "\n```\n")
		}
		if s.Stderr != "" {
			b.WriteString("\n<details><summary>captured stderr</summary>\n\n```\n" +
				s.Stderr + "\n```\n\n</details>\n")
		}
	}

	if len(rt.Jobs) > 0 {
		b.WriteString("\n**Recent generations**\n\n")
		b.WriteString("| id | status | bytes | error |\n|---|---|---|---|\n")
		for _, j := range rt.Jobs {
			fmt.Fprintf(b, "| `%s` | %s | %d | %s |\n",
				shortID(j.ID), j.Status, j.Bytes, cell(j.Error))
		}
	}
	closeDetails(b)
}

func (r Report) writeSystem(b *strings.Builder) {
	s := r.System
	open(b, "System")

	fmt.Fprintf(b, "- %s · %s/%s · %d CPU · %s RAM\n",
		orDash(s.OSVersion), r.Build.OS, r.Build.Arch, s.NumCPU, humanBytes(s.TotalRAM))
	fmt.Fprintf(b, "- host `%s` · user `%s` · elevated %t\n",
		orDash(s.Hostname), orDash(s.User), s.Elevated)

	// Locale first among the details: it is the field that decides whether the
	// paths below can be read at face value.
	b.WriteString("\n**Locale**\n\n")
	if s.Locale.UserLocale != "" || s.Locale.ANSICodePage != 0 {
		fmt.Fprintf(b, "- locale `%s` · ANSI CP %d · OEM CP %d · console out CP %d · console in CP %d\n",
			orDash(s.Locale.UserLocale), s.Locale.ANSICodePage, s.Locale.OEMCodePage,
			s.Locale.ConsoleOutputCodePage, s.Locale.ConsoleInputCodePage)
	} else {
		fmt.Fprintf(b, "- effective `%s`\n", orDash(s.Locale.Effective))
		for k, v := range s.Locale.Env {
			fmt.Fprintf(b, "  - %s=%s\n", k, v)
		}
	}
	for _, n := range s.Locale.Notes {
		b.WriteString("- ⚠ " + n + "\n")
	}

	b.WriteString("\n**Paths**\n\n")
	b.WriteString("| what | path | state | free |\n|---|---|---|---|\n")
	for _, p := range s.Paths {
		state := []string{}
		if p.Exists {
			state = append(state, "exists")
			if p.Writable {
				state = append(state, "writable")
			} else {
				state = append(state, "NOT writable")
			}
		} else if p.Error != "" {
			state = append(state, p.Error)
		}
		if !p.Absolute && p.Raw != "" {
			state = append(state, "relative")
		}
		if p.NonASCII {
			state = append(state, "non-ASCII: `"+shortHex(p.Bytes, 80)+"`")
		}
		if !p.ValidUTF8 {
			state = append(state, "**not valid UTF-8**")
		}
		if p.VolumeType != "" {
			state = append(state, p.Volume+" is "+p.VolumeType)
		}
		fmt.Fprintf(b, "| %s | `%s` | %s | %s |\n",
			p.Label, p.Raw, strings.Join(state, ", "), humanBytes(p.FreeBytes))
	}

	if len(s.Env) > 0 {
		b.WriteString("\n**Environment**\n\n")
		for k, v := range s.Env {
			fmt.Fprintf(b, "- `%s=%s`\n", k, v)
		}
	}
	closeDetails(b)
}

func (r Report) writeConfig(b *strings.Builder) {
	c := r.Config
	open(b, "Configuration")

	fmt.Fprintf(b, "- `%s` · exists %t · modified %s\n", c.Path, c.Exists, orDash(c.Modified))
	fmt.Fprintf(b, "- mode **%s**", c.Mode)
	if c.ModeError != "" {
		fmt.Fprintf(b, " (%s)", c.ModeError)
	}
	b.WriteString("\n")
	if c.PerfOverridden {
		fmt.Fprintf(b, "- ⚠ perf.toml is applied on top of config.toml — "+
			"detected baseline was ctx %d / gpu_layers %d / kv %s\n",
			c.AutoCtxSize, c.AutoGPULayers, c.AutoKVCacheType)
	}
	for _, d := range c.Deferred {
		b.WriteString("- ⚠ " + d + "\n")
	}

	// Changed settings first and separately. It is a short list, it is where
	// the problem usually is, and a reader should not have to diff two dozen
	// rows by eye to find it.
	var changed, rest []ConfigEntry
	for _, e := range c.Entries {
		if e.Changed {
			changed = append(changed, e)
		} else {
			rest = append(rest, e)
		}
	}

	b.WriteString("\n**Changed from defaults**\n\n")
	if len(changed) == 0 {
		b.WriteString("_none — this is a stock configuration._\n")
	} else {
		b.WriteString("| key | value | default |\n|---|---|---|\n")
		for _, e := range changed {
			fmt.Fprintf(b, "| `%s` | %s | %s |\n", e.Key, cell(e.Value), cell(orDash(e.Default)))
		}
	}

	if len(rest) > 0 {
		b.WriteString("\n<details><summary>at defaults</summary>\n\n")
		b.WriteString("| key | value |\n|---|---|\n")
		for _, e := range rest {
			fmt.Fprintf(b, "| `%s` | %s |\n", e.Key, cell(e.Value))
		}
		b.WriteString("\n</details>\n")
	}
	closeDetails(b)
}

func (r Report) writeData(b *strings.Builder) {
	d := r.Data
	open(b, "Saved data")

	b.WriteString("| file | role | threads | messages | cards | size |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, f := range d.Files {
		if !f.Exists {
			fmt.Fprintf(b, "| `%s` | %s | — | — | — | absent |\n", f.Name, f.Role)
			continue
		}
		fmt.Fprintf(b, "| `%s` | %s | %d | %d | %d | %s |\n",
			f.Name, f.Role, f.Threads, f.Messages, f.CharacterCards, humanBytes(f.Size))
	}
	for _, f := range d.Files {
		if f.Error != "" {
			fmt.Fprintf(b, "\n- ⚠ `%s`: %s\n", f.Name, f.Error)
		}
	}
	for _, f := range d.Findings {
		b.WriteString("\n- ⚠ " + f + "\n")
	}
	if !d.SchemaVersionSupported {
		b.WriteString("\n- note: the state format carries no schema version, " +
			"so its age can only be inferred from the key set below.\n")
	}
	for _, f := range d.Files {
		if f.Exists && len(f.Keys) > 0 {
			fmt.Fprintf(b, "- `%s` keys: %s\n", f.Name, strings.Join(f.Keys, ", "))
		}
	}
	closeDetails(b)
}

func (r Report) writeModels(b *strings.Builder) {
	m := r.Models
	open(b, fmt.Sprintf("Models (%d found)", len(m.Files)))

	fmt.Fprintf(b, "- `%s` · usable %t · %s free\n", m.Dir, m.Usable, humanBytes(m.FreeBytes))
	if m.Error != "" {
		b.WriteString("- ⚠ " + m.Error + "\n")
	}
	for _, p := range m.Partial {
		b.WriteString("- ⚠ partial download left behind: `" + p + "`\n")
	}

	if len(m.Files) > 0 {
		b.WriteString("\n| file | size | classified as | jinja | template |\n")
		b.WriteString("|---|---|---|---|---|\n")
		for _, f := range m.Files {
			tmpl := f.ChatTemplate
			if f.ChatTemplateFile != "" {
				tmpl = "sidecar: " + f.ChatTemplateFile
			}
			active := ""
			if f.Active {
				active = " **(active)**"
			}
			fmt.Fprintf(b, "| `%s`%s | %s | %s / %s | %d | %s |\n",
				f.File, active, humanBytes(f.Size), orDash(f.Family), orDash(f.ID),
				f.UseJinja, cell(orDash(tmpl)))
		}
	}
	closeDetails(b)
}

// --- helpers ---------------------------------------------------------------

func open(b *strings.Builder, title string) {
	b.WriteString("\n<details open><summary><b>" + title + "</b></summary>\n\n")
}

func closeDetails(b *strings.Builder) { b.WriteString("\n</details>\n") }

func code(s string) string {
	if s == "" {
		return "—"
	}
	return "`" + s + "`"
}

func orDash(s string) string {
	if s == "" {
		return "—"
	}
	return s
}

// cell makes a value safe for a markdown table: pipes would end the cell and
// newlines would end the row, so both are neutralised rather than dropped.
func cell(s string) string {
	if s == "" {
		return "—"
	}
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\r\n", " ")
	s = strings.ReplaceAll(s, "\n", "<br>")
	return s
}

func shortID(s string) string {
	if len(s) > 8 {
		return s[:8]
	}
	return s
}

// FormatUptime renders a duration for the Runtime section.
func FormatUptime(d time.Duration) string {
	d = d.Round(time.Second)
	if d < time.Minute {
		return d.String()
	}
	return d.Truncate(time.Second).String()
}
